version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    command: start-dev --import-realm
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_IMPORT_FILE: /keycloak/data/import/realm-export.json
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./keycloak:/opt/keycloak/data/import
  db:
    image: postgres:15
    container_name: lr-oop-db
    environment:
      POSTGRES_DB: lr_oop_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
      - ./src/main/resources/scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  backend:
    build: .
    container_name: lr-oop-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lr_oop_db
      DB_USER: postgres_user
      DB_PASS: postgres_pass

  frontend:
    image: nginx:alpine
    container_name: lr-oop-frontend
    ports:
      - "3000:80"
    volumes:
      - ./src/main/java/ui:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  pg:

