openapi: 3.0.3
info:
  title: Function Storage API
  version: 1.0.0
  description: |
    Единый унифицированный контракт API для лабораторных работ №6 и №7.
    Поддерживает операции CRUD и поиск для табулированных функций (TabulatedFunctionDTO).
    Основан на реализации из лабораторной работы №5.

servers:
  - url: http://localhost:8080/api
    description: |
      Local development (manual: Tomcat, framework: Spring Boot)

security:
  - BasicAuth: []

paths:
  /functions:
    post:
      summary: Создать новую табулированную функцию
      tags: [Functions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCreateRequest'
      responses:
        '201':
          description: Функция создана
          headers:
            Location:
              schema:
                type: string
                example: /api/functions/123
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'

  /functions/{id}:
    get:
      summary: Получить функцию по ID (только владельцу)
      tags: [Functions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Функция найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Функция не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Обновить имя и/или данные функции (только владельцу)
      tags: [Functions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionUpdateRequest'
      responses:
        '200':
          description: Функция обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionResponse'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Удалить функцию (только владельцу)
      tags: [Functions]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешно удалено
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/owner/{ownerId}:
    get:
      summary: Получить все функции пользователя
      tags: [Functions]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список функций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /functions/owner/{ownerId}/type/{typeId}:
    get:
      summary: Получить функции пользователя по типу
      tags: [Functions]
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
        - name: typeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Список функций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FunctionResponse'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    FunctionCreateRequest:
      type: object
      required: [ownerId, typeId, name, serializedData]
      properties:
        ownerId:
          type: integer
          example: 1
        typeId:
          type: integer
          description: ID типа функции (1 = Tabulated, 2 = SIN и т.д.)
          example: 1
        name:
          type: string
          maxLength: 100
          example: "my_quadratic"
        serializedData:
          type: string
          format: byte
          description: Сериализованные точки (x[], y[]) в base64

    FunctionUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          example: "renamed"
        serializedData:
          type: string
          format: byte
          description: Новые точки (если нужно заменить данные)

    FunctionResponse:
      type: object
      properties:
        id:
          type: integer
        ownerId:
          type: integer
        typeId:
          type: integer
        name:
          type: string
        serializedData:
          type: string
          format: byte
        createdAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "ValidationFailed"
        message:
          type: string
          example: "Поле 'name' не может быть пустым"
        field:
          type: string
          example: "name"
        timestamp:
          type: string
          format: date-time